# Generated by Django 4.1.4 on 2022-12-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='session',
            field=models.IntegerField(default=0.9995051954477981, null=True),
        ),
    ]
